import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom'
import { Layout } from './components/Layout'
import { ProtectedRoute } from './components/ProtectedRoute'
import { AuthProvider } from './context/AuthContext'
import { FinanceProvider } from './context/FinanceContext'
import { Access } from './pages/Access'
import { Budgets } from './pages/Budgets'
import { Dashboard } from './pages/Dashboard'
import { Goals } from './pages/Goals'
import { Login } from './pages/Login'
import { Recurring } from './pages/Recurring'
import { Reports } from './pages/Reports'
import { Settings } from './pages/Settings'
import { Transactions } from './pages/Transactions'
export default function App(){return <BrowserRouter><AuthProvider><FinanceProvider><Routes><Route path="/entrar" element={<Login/>}/><Route path="/acesso" element={<Access/>}/><Route element={<ProtectedRoute/>}><Route element={<Layout/>}><Route path="/dashboard" element={<Dashboard/>}/><Route path="/transacoes" element={<Transactions/>}/><Route path="/orcamentos" element={<Budgets/>}/><Route path="/metas" element={<Goals/>}/><Route path="/recorrentes" element={<Recurring/>}/><Route path="/relatorios" element={<Reports/>}/><Route path="/configuracoes" element={<Settings/>}/></Route></Route><Route path="*" element={<Navigate to="/dashboard" replace/>}/></Routes></FinanceProvider></AuthProvider></BrowserRouter>}
